"""
Branch Models - Auto-generated from SQL dump
Generated by scripts/generate_models.py
"""

from sqlalchemy import Column, String, Text, Integer, BigInteger, SmallInteger
from sqlalchemy import Boolean, DECIMAL, Float, DateTime, Date, Time
from sqlalchemy import ForeignKey, Index, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import UUID, JSONB, JSON
from sqlalchemy.sql import func
from app.core.db_session import Base
import uuid


class BranchContactTable(Base):
    """Auto-generated model for branch_contact_table table"""
    __tablename__ = "branch_contact_table"

    branch_contact_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    branch_id = Column(UUID(as_uuid=True), index=True)
    contact_type = Column(String(255), )
    contact_value = Column(String(255), )
    is_primary = Column(Boolean, default=False)
    contact_label = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class BranchInfoTable(Base):
    """Auto-generated model for branch_info_table table"""
    __tablename__ = "branch_info_table"

    branch_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    chain_id = Column(UUID(as_uuid=True), index=True)
    branch_name = Column(String(255), nullable=False)
    branch_website_url = Column(Text, )
    branch_logo_url = Column(Text, )
    branch_personalized_greeting = Column(Text, )
    is_active = Column(Boolean, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
    ext_petpooja_restaurant_id = Column(String(255), )

class BranchLocationTable(Base):
    """Auto-generated model for branch_location_table table"""
    __tablename__ = "branch_location_table"

    branch_location_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    branch_id = Column(UUID(as_uuid=True), index=True)
    address_line = Column(Text, )
    landmark = Column(Text, )
    pincode_id = Column(UUID(as_uuid=True), index=True)
    latitude = Column(DECIMAL(precision=10, scale=8), )
    longitude = Column(DECIMAL(precision=11, scale=8), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class BranchTimingPolicy(Base):
    """Auto-generated model for branch_policy table"""
    __tablename__ = "branch_policy"

    branch_timing_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    opening_time = Column(Time, )
    closing_time = Column(Time, )
    food_ordering_start_time = Column(Time, )
    food_ordering_closing_time = Column(Time, )
    table_booking_open_time = Column(Time, )
    table_booking_close_time = Column(Time, )
    order_type = Column(String(255), )
    minimum_order_amount = Column(DECIMAL(precision=5, scale=2), )
    minimum_delivery_time_min = Column(Integer, )
    delivery_charge = Column(DECIMAL(precision=5, scale=2), )
    minimum_prep_time_min = Column(Integer, )
    calculate_tax_on_packing = Column(Boolean, )
    calculate_tax_on_delivery = Column(Boolean, )
    packaging_applicable_on = Column(String(255), )
    packaging_charge = Column(DECIMAL(precision=5, scale=2), )
    packaging_charge_type = Column(String(255), )
    delivery_hours_from1 = Column(Time, )
    delivery_hours_to1 = Column(Time, )
    delivery_hours_from2 = Column(Time, )
    delivery_hours_to2 = Column(Time, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
