"""
Customer Models - Auto-generated from SQL dump
Generated by scripts/generate_models.py
"""

from sqlalchemy import Column, String, Text, Integer, BigInteger, SmallInteger
from sqlalchemy import Boolean, DECIMAL, Float, DateTime, Date, Time
from sqlalchemy import ForeignKey, Index, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import UUID, JSONB, JSON
from sqlalchemy.sql import func
from app.core.db_session import Base
import uuid


class CustomerActivityLog(Base):
    """Auto-generated model for customer_activity_log table"""
    __tablename__ = "customer_activity_log"

    log_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    activity_type = Column(String(255), )
    activity_timestamp = Column(DateTime(timezone=True), server_default=func.now())
    ip_address = Column(String(255), )
    user_agent = Column(String(255), )
    details = Column(JSONB, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerAddressTable(Base):
    """Auto-generated model for customer_address_table table"""
    __tablename__ = "customer_address_table"

    customer_address_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    customer_address_type = Column(String(255), )
    customer_address_label = Column(String(255), )
    customer_street_address_1 = Column(Text, )
    customer_street_address_2 = Column(Text, )
    customer_city = Column(Text, )
    customer_state_province = Column(Text, )
    customer_postal_code = Column(Text, )
    customer_country = Column(Text, )
    customer_latitude = Column(DECIMAL(precision=10, scale=8), )
    customer_longitude = Column(DECIMAL(precision=11, scale=8), )
    customer_is_default = Column(Boolean, default=False)
    customer_delivery_instructions = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerAllergens(Base):
    """Auto-generated model for customer_allergens table"""
    __tablename__ = "customer_allergens"

    customer_id = Column(UUID(as_uuid=True), primary_key=True, index=True)
    allergen_id = Column(UUID(as_uuid=True), primary_key=True, index=True)
    customer_allergen_severity = Column(String(255), )
    customer_allergen_notes = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerAuthentication(Base):
    """Auto-generated model for customer_authentication table"""
    __tablename__ = "customer_authentication"

    auth_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    auth_method = Column(String(255), )
    auth_provider = Column(String(255), )
    password_hash = Column(Text, )
    last_login = Column(DateTime(timezone=True), )
    failed_attempts = Column(Integer, server_default=text("'0'"))
    locked_until = Column(DateTime(timezone=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerConsent(Base):
    """Auto-generated model for customer_consent table"""
    __tablename__ = "customer_consent"

    consent_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    consent_type = Column(String(255), )
    consent_given = Column(Boolean, default=True)
    consent_date = Column(DateTime(timezone=True), server_default=func.now())
    consent_withdrawn_at = Column(DateTime(timezone=True), )
    consent_method = Column(String(255), )
    ip_address = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerContactTable(Base):
    """Auto-generated model for customer_contact_table table"""
    __tablename__ = "customer_contact_table"

    contact_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    customer_contact_type = Column(String(255), )
    customer_contact_value = Column(String(255), )
    customer_is_primary = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerDevices(Base):
    """Auto-generated model for customer_devices table"""
    __tablename__ = "customer_devices"

    device_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    device_type = Column(String(255), )
    device_name = Column(String(255), )
    os = Column(String(255), )
    browser = Column(String(255), )
    first_seen = Column(DateTime(timezone=True), )
    last_seen = Column(DateTime(timezone=True), )
    is_trusted = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerDietaryRestrictions(Base):
    """Auto-generated model for customer_dietary_restrictions table"""
    __tablename__ = "customer_dietary_restrictions"

    customer_id = Column(UUID(as_uuid=True), primary_key=True, index=True)
    dietary_restriction_id = Column(UUID(as_uuid=True), primary_key=True, index=True)
    customer_dietary_restriction_severity = Column(String(255), )
    customer_dietary_restriction_notes = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerFavoriteItems(Base):
    """Auto-generated model for customer_favorite_items table"""
    __tablename__ = "customer_favorite_items"

    favorite_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    menu_item_id = Column(UUID(as_uuid=True), index=True)
    added_at = Column(DateTime(timezone=True), server_default=func.now())
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerGender(Base):
    """Auto-generated model for customer_gender table"""
    __tablename__ = "customer_gender"

    customer_gender_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    customer_gender_name = Column(String(255), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerPreferences(Base):
    """Auto-generated model for customer_preferences table"""
    __tablename__ = "customer_preferences"

    customer_preference_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerProfileTable(Base):
    """Auto-generated model for customer_profile_table table"""
    __tablename__ = "customer_profile_table"

    customer_id = Column(UUID(as_uuid=True), primary_key=True, index=True)
    customer_first_name = Column(String(255), )
    customer_last_name = Column(String(255), )
    customer_display_name = Column(String(255), )
    customer_date_of_birth = Column(Date, )
    customer_gender_id = Column(UUID(as_uuid=True), index=True)
    language_id = Column(UUID(as_uuid=True), index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerSearchQueries(Base):
    """Auto-generated model for customer_search_queries table"""
    __tablename__ = "customer_search_queries"

    query_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    conversation_id = Column(UUID(as_uuid=True), index=True)
    search_query = Column(Text, )
    search_timestamp = Column(DateTime(timezone=True), server_default=func.now())
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerSessions(Base):
    """Auto-generated model for customer_sessions table"""
    __tablename__ = "customer_sessions"

    session_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    session_token = Column(Text, )
    expires_at = Column(DateTime(timezone=True), )
    ip_address = Column(String(255), )
    user_agent = Column(String(255), )
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerInfoTable(Base):
    """Model for customer_info_table - stores basic customer information"""
    __tablename__ = "customer_info_table"

    customer_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    customer_name = Column(String(255), )
    customer_phone = Column(String(50), )
    customer_email = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerTagMapping(Base):
    """Auto-generated model for customer_tag_mapping table"""
    __tablename__ = "customer_tag_mapping"

    customer_id = Column(UUID(as_uuid=True), primary_key=True, index=True)
    tag_id = Column(UUID(as_uuid=True), primary_key=True, index=True)
    tagged_by = Column(UUID(as_uuid=True), )
    tagged_at = Column(DateTime(timezone=True), server_default=func.now())
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class CustomerTags(Base):
    """Auto-generated model for customer_tags table"""
    __tablename__ = "customer_tags"

    tag_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    tag_name = Column(String(255), nullable=False)
    tag_category = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
