"""
Feedback Models - Auto-generated from SQL dump
Generated by scripts/generate_models.py
"""

from sqlalchemy import Column, String, Text, Integer, BigInteger, SmallInteger
from sqlalchemy import Boolean, DECIMAL, Float, DateTime, Date, Time
from sqlalchemy import ForeignKey, Index, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import UUID, JSONB, JSON
from sqlalchemy.sql import func
from app.core.db_session import Base
import uuid


class FeedbackAttachments(Base):
    """Auto-generated model for feedback_attachments table"""
    __tablename__ = "feedback_attachments"

    attachment_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    feedback_id = Column(UUID(as_uuid=True), index=True)
    file_name = Column(String(255), nullable=False)
    file_path = Column(Text, nullable=False)
    file_type = Column(String(20), )
    file_size = Column(BigInteger, )
    uploaded_by = Column(UUID(as_uuid=True), )
    uploaded_at = Column(DateTime(timezone=True), server_default=func.now())
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class FeedbackCategories(Base):
    """Auto-generated model for feedback_categories table"""
    __tablename__ = "feedback_categories"

    category_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    category_name = Column(String(255), nullable=False)
    description = Column(Text, )
    icon = Column(Text, )
    display_order = Column(Integer, server_default=text("'0'"))
    is_active = Column(Boolean, default=True)
    parent_category_id = Column(UUID(as_uuid=True), index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class FeedbackNotifications(Base):
    """Auto-generated model for feedback_notifications table"""
    __tablename__ = "feedback_notifications"

    notification_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    feedback_id = Column(UUID(as_uuid=True), index=True)
    recipient_email = Column(String(255), nullable=False)
    notification_type = Column(String(20), )
    subject = Column(Text, )
    sent_at = Column(DateTime(timezone=True), server_default=func.now())
    opened_at = Column(DateTime(timezone=True), )
    clicked_at = Column(DateTime(timezone=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class FeedbackPlatforms(Base):
    """Auto-generated model for feedback_platforms table"""
    __tablename__ = "feedback_platforms"

    platform_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    platform_name = Column(String(255), nullable=False)
    platform_type = Column(String(20), )
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class FeedbackPriorities(Base):
    """Auto-generated model for feedback_priorities table"""
    __tablename__ = "feedback_priorities"

    priority_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    priority_name = Column(String(255), nullable=False)
    priority_level = Column(Integer, )
    color_code = Column(String(20), )
    response_sla_hours = Column(Integer, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class FeedbackPriorityHistory(Base):
    """Auto-generated model for feedback_priority_history table"""
    __tablename__ = "feedback_priority_history"

    history_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    feedback_id = Column(UUID(as_uuid=True), index=True)
    old_priority_id = Column(UUID(as_uuid=True), index=True)
    new_priority_id = Column(UUID(as_uuid=True), index=True)
    changed_by = Column(UUID(as_uuid=True), )
    changed_at = Column(DateTime(timezone=True), server_default=func.now())
    change_reason = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class FeedbackResponses(Base):
    """Auto-generated model for feedback_responses table"""
    __tablename__ = "feedback_responses"

    response_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    feedback_id = Column(UUID(as_uuid=True), index=True)
    responded_by = Column(UUID(as_uuid=True), )
    response_text = Column(Text, nullable=False)
    is_internal = Column(Boolean, default=False)
    is_automated = Column(Boolean, default=False)
    is_public = Column(Boolean, default=False)
    response_at = Column(DateTime(timezone=True), server_default=func.now())
    edited_at = Column(DateTime(timezone=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class FeedbackStatusHistory(Base):
    """Auto-generated model for feedback_status_history table"""
    __tablename__ = "feedback_status_history"

    history_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    feedback_id = Column(UUID(as_uuid=True), index=True)
    old_status_id = Column(UUID(as_uuid=True), index=True)
    new_status_id = Column(UUID(as_uuid=True), index=True)
    changed_by = Column(UUID(as_uuid=True), )
    changed_at = Column(DateTime(timezone=True), server_default=func.now())
    change_reason = Column(Text, )
    is_automated = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class FeedbackStatuses(Base):
    """Auto-generated model for feedback_statuses table"""
    __tablename__ = "feedback_statuses"

    status_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    status_name = Column(String(255), nullable=False)
    description = Column(Text, )
    color_code = Column(String(255), )
    is_initial = Column(Boolean, default=False)
    is_final = Column(Boolean, default=False)
    display_order = Column(Integer, server_default=text("'0'"))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class FeedbackTags(Base):
    """Auto-generated model for feedback_tags table"""
    __tablename__ = "feedback_tags"

    feedback_id = Column(UUID(as_uuid=True), primary_key=True, index=True)
    tag_id = Column(UUID(as_uuid=True), primary_key=True, index=True)
    added_by = Column(UUID(as_uuid=True), )
    added_at = Column(DateTime(timezone=True), server_default=func.now())
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class FeedbackTypes(Base):
    """Auto-generated model for feedback_types table"""
    __tablename__ = "feedback_types"

    type_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    type_name = Column(String(255), nullable=False)
    description = Column(Text, )
    color_code = Column(String(20), )
    icon = Column(Text, )
    requires_response = Column(Boolean, default=True)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
