"""
Integration Models - Auto-generated from SQL dump
Generated by scripts/generate_models.py
"""

from sqlalchemy import Column, String, Text, Integer, BigInteger, SmallInteger
from sqlalchemy import Boolean, DECIMAL, Float, DateTime, Date, Time
from sqlalchemy import ForeignKey, Index, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import UUID, JSONB, JSON
from sqlalchemy.sql import func
from app.core.db_session import Base
import uuid


class IntegrationConfigTable(Base):
    """Auto-generated model for integration_config_table table"""
    __tablename__ = "integration_config_table"

    integration_config_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    provider_id = Column(UUID(as_uuid=True), index=True)
    is_enabled = Column(Boolean, default=False)
    api_key = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class IntegrationCredentialsTable(Base):
    """Auto-generated model for integration_credentials_table table"""
    __tablename__ = "integration_credentials_table"

    credential_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    integration_config_id = Column(UUID(as_uuid=True), index=True)
    credential_key = Column(String(255), )
    credential_value = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class IntegrationMetadataTable(Base):
    """Auto-generated model for integration_metadata_table table"""
    __tablename__ = "integration_metadata_table"

    metadata_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    integration_config_id = Column(UUID(as_uuid=True), index=True)
    metadata_key = Column(String(255), )
    metadata_value = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class IntegrationProviderTable(Base):
    """Auto-generated model for integration_provider_table table"""
    __tablename__ = "integration_provider_table"

    provider_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    provider_name = Column(String(255), nullable=False)
    provider_description = Column(Text, )
    provider_base_url = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
