"""
Menu Models - Auto-generated from SQL dump
Generated by scripts/generate_models.py
"""

from sqlalchemy import Column, String, Text, Integer, BigInteger, SmallInteger
from sqlalchemy import Boolean, DECIMAL, Float, DateTime, Date, Time
from sqlalchemy import ForeignKey, Index, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import UUID, JSONB, JSON
from sqlalchemy.sql import func
from app.core.db_session import Base
import uuid


class ComboItem(Base):
    """Auto-generated model for combo_item table"""
    __tablename__ = "combo_item"

    combo_item_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    combo_item_component_id = Column(UUID(as_uuid=True), index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    combo_type = Column(String(255), )
    is_available = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class ComboItemComponents(Base):
    """Auto-generated model for combo_item_components table"""
    __tablename__ = "combo_item_components"

    combo_item_component_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    combo_item_id = Column(UUID(as_uuid=True), index=True)
    menu_item_id = Column(UUID(as_uuid=True), index=True)
    quantity = Column(Integer, server_default=text("'1'"))
    is_optional = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class MenuCategories(Base):
    """Auto-generated model for menu_categories table"""
    __tablename__ = "menu_categories"

    menu_category_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    menu_category_status = Column(String(20), )
    menu_category_rank = Column(Integer, )
    menu_category_name = Column(String(255), )
    menu_category_description = Column(Text, )
    menu_category_timings = Column(Text, )
    menu_category_image_url = Column(Text, )
    menu_parent_category_id = Column(UUID(as_uuid=True), index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
    ext_petpooja_group_category_id = Column(BigInteger, )

class MenuItem(Base):
    """Auto-generated model for menu_item table"""
    __tablename__ = "menu_item"

    menu_item_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    menu_sub_category_id = Column(UUID(as_uuid=True), index=True)
    menu_item_name = Column(String(255), )
    menu_item_status = Column(String(20), )
    menu_item_description = Column(Text, )
    menu_item_price = Column(DECIMAL(precision=12, scale=2), server_default=text("'0'"))
    menu_item_allow_variation = Column(Boolean, default=False)
    menu_item_allow_addon = Column(Boolean, default=False)
    menu_item_minimum_preparation_time = Column(Integer, )
    menu_item_tax_id = Column(UUID(as_uuid=True), index=True)
    menu_item_tax_cgst = Column(DECIMAL(precision=8, scale=2), )
    menu_item_tax_sgst = Column(DECIMAL(precision=8, scale=2), )
    menu_item_timings = Column(Text, )
    menu_item_packaging_charges = Column(DECIMAL(precision=10, scale=2), server_default=text("'0'"))
    menu_item_attribute_id = Column(UUID(as_uuid=True), index=True)
    menu_item_rank = Column(Integer, )
    menu_item_favorite = Column(Boolean, default=False)
    menu_item_ignore_taxes = Column(Boolean, default=False)
    menu_item_ignore_discounts = Column(Boolean, default=False)
    menu_item_in_stock = Column(Boolean, default=True)
    menu_item_is_combo = Column(Boolean, default=False)
    menu_item_is_recommended = Column(Boolean, default=False)
    menu_item_spice_level = Column(String(50), )
    menu_item_addon_based_on = Column(Text, )
    menu_item_markup_price = Column(DECIMAL(precision=12, scale=2), )
    menu_item_is_combo_parent = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
    ext_petpooja_item_id = Column(BigInteger, )
    # Chatbot-specific columns for enhanced menu features
    menu_item_quantity = Column(Integer, server_default=text("'0'"))
    menu_item_calories = Column(Integer, )
    menu_item_is_seasonal = Column(Boolean, default=False)
    menu_item_image_url = Column(String(500), )
    menu_item_serving_unit = Column(String(20), )

class MenuItemAddonGroup(Base):
    """Auto-generated model for menu_item_addon_group table"""
    __tablename__ = "menu_item_addon_group"

    menu_item_addon_group_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    menu_item_addon_group_name = Column(String(255), )
    menu_item_addon_group_rank = Column(Integer, )
    menu_item_addon_group_status = Column(String(20), )
    menu_item_addon_group_selection_min = Column(Integer, )
    menu_item_addon_group_selection_max = Column(Integer, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
    ext_petpooja_addon_group_id = Column(BigInteger, )

class MenuItemAddonItem(Base):
    """Auto-generated model for menu_item_addon_item table"""
    __tablename__ = "menu_item_addon_item"

    menu_item_addon_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    menu_item_addon_group_id = Column(UUID(as_uuid=True), index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    menu_item_addon_item_name = Column(String(255), )
    menu_item_addon_item_price = Column(DECIMAL(precision=10, scale=2), )
    menu_item_addon_item_status = Column(String(20), )
    menu_item_addon_item_rank = Column(Integer, )
    menu_item_addon_item_attribute_id = Column(UUID(as_uuid=True), index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
    ext_petpooja_addon_item_id = Column(BigInteger, )

class MenuItemAddonMapping(Base):
    """Auto-generated model for menu_item_addon_mapping table"""
    __tablename__ = "menu_item_addon_mapping"

    menu_item_addon_mapping_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    menu_item_id = Column(UUID(as_uuid=True), index=True)
    menu_item_variation_id = Column(UUID(as_uuid=True), index=True)
    menu_item_addon_group_id = Column(UUID(as_uuid=True), index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class MenuItemAttribute(Base):
    """Auto-generated model for menu_item_attribute table"""
    __tablename__ = "menu_item_attribute"

    menu_item_attribute_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    menu_item_attribute_name = Column(String(255), )
    menu_item_attribute_status = Column(String(20), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
    ext_petpooja_attributes_id = Column(BigInteger, )
    restaurant_id = Column(UUID(as_uuid=True), index=True)

class MenuItemAvailabilitySchedule(Base):
    """Auto-generated model for menu_item_availability_schedule table"""
    __tablename__ = "menu_item_availability_schedule"

    schedule_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    menu_item_id = Column(UUID(as_uuid=True), index=True)
    day_of_week = Column(String(255), )
    time_from = Column(Time, )
    time_to = Column(Time, )
    is_available = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class MenuItemCuisineMapping(Base):
    """Auto-generated model for menu_item_cuisine_mapping table"""
    __tablename__ = "menu_item_cuisine_mapping"

    menu_item_cuisine_mapping_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    menu_item_id = Column(UUID(as_uuid=True), index=True)
    cuisine_id = Column(UUID(as_uuid=True), index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class MenuItemDiscountMapping(Base):
    """Auto-generated model for menu_item_discount_mapping table"""
    __tablename__ = "menu_item_discount_mapping"

    menu_item_discount_mapping_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    menu_item_id = Column(UUID(as_uuid=True), index=True)
    discount_id = Column(UUID(as_uuid=True), index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class MenuItemOption(Base):
    """Auto-generated model for menu_item_option table"""
    __tablename__ = "menu_item_option"

    menu_item_option_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    menu_item_id = Column(UUID(as_uuid=True), index=True)
    menu_item_option_name = Column(String(255), )
    menu_item_option_description = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class MenuItemOrdertypeMapping(Base):
    """Auto-generated model for menu_item_ordertype_mapping table"""
    __tablename__ = "menu_item_ordertype_mapping"

    menu_item_ordertype_mapping_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    menu_item_id = Column(UUID(as_uuid=True), index=True)
    menu_item_ordertype_id = Column(UUID(as_uuid=True), index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class MenuItemTag(Base):
    """Auto-generated model for menu_item_tag table"""
    __tablename__ = "menu_item_tag"

    menu_item_tag_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    menu_item_tag_name = Column(String(255), )
    menu_item_tag_status = Column(String(20), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class MenuItemTagMapping(Base):
    """Auto-generated model for menu_item_tag_mapping table"""
    __tablename__ = "menu_item_tag_mapping"

    menu_item_tag_mapping_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    menu_item_id = Column(UUID(as_uuid=True), index=True)
    menu_item_tag_id = Column(UUID(as_uuid=True), index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class MenuItemTaxMapping(Base):
    """Auto-generated model for menu_item_tax_mapping table"""
    __tablename__ = "menu_item_tax_mapping"

    menu_item_tax_mapping_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    menu_item_id = Column(UUID(as_uuid=True), index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    tax_id = Column(UUID(as_uuid=True), index=True)
    is_tax_inclusive = Column(Boolean, default=False)
    gst_liability = Column(Text, )
    gst_type = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class MenuItemVariation(Base):
    """Auto-generated model for menu_item_variation table"""
    __tablename__ = "menu_item_variation"

    menu_item_variation_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    menu_item_id = Column(UUID(as_uuid=True), index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    variation_group_id = Column(UUID(as_uuid=True), index=True)
    menu_item_variation_name = Column(String(255), )
    menu_item_variation_price = Column(DECIMAL(precision=12, scale=2), )
    menu_item_variation_markup_price = Column(DECIMAL(precision=12, scale=2), )
    menu_item_variation_status = Column(String(20), )
    menu_item_variation_rank = Column(Integer, )
    menu_item_variation_allow_addon = Column(Boolean, default=False)
    menu_item_variation_packaging_charges = Column(DECIMAL(precision=10, scale=2), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
    ext_petpooja_variation_id = Column(BigInteger, )

class MenuItemVariationMapping(Base):
    """Auto-generated model for menu_item_variation_mapping table"""
    __tablename__ = "menu_item_variation_mapping"

    menu_item_variation_mapping_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    menu_item_id = Column(UUID(as_uuid=True), index=True)
    menu_item_variation_group_id = Column(UUID(as_uuid=True), index=True)
    menu_item_variation_rank = Column(Integer, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class MenuSections(Base):
    """Auto-generated model for menu_sections table"""
    __tablename__ = "menu_sections"

    menu_section_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    menu_section_status = Column(String(20), )
    menu_section_name = Column(String(255), )
    menu_section_description = Column(Text, )
    menu_section_image_url = Column(Text, )
    menu_section_rank = Column(Integer, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
    ext_petpooja_parent_categories_id = Column(BigInteger, nullable=False)  # NOT NULL in database

class MenuSubCategories(Base):
    """Auto-generated model for menu_sub_categories table"""
    __tablename__ = "menu_sub_categories"

    menu_sub_category_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    category_id = Column(UUID(as_uuid=True), index=True)
    sub_category_status = Column(String(20), )
    sub_category_rank = Column(Integer, )
    sub_category_name = Column(String(255), )
    sub_category_description = Column(Text, )
    sub_category_timings = Column(Text, )
    sub_category_image_url = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
    ext_petpooja_categories_id = Column(BigInteger, )
    menu_section_id = Column(UUID(as_uuid=True), index=True)  # New column from latest DB schema

class MenuSyncLog(Base):
    """Auto-generated model for menu_sync_log table"""
    __tablename__ = "menu_sync_log"

    menu_sync_log_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    menu_sync_source = Column(Text, )
    menu_sync_status = Column(String(20), )
    menu_sync_started_at = Column(DateTime(timezone=True), )
    menu_sync_completed_at = Column(DateTime(timezone=True), )
    menu_items_synced = Column(JSONB, )
    menu_errors = Column(JSONB, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class MenuVersionHistory(Base):
    """Auto-generated model for menu_version_history table"""
    __tablename__ = "menu_version_history"

    menu_version_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    menu_version_number = Column(Integer, )
    menu_version_changed_by = Column(UUID(as_uuid=True), )
    menu_version_change_summary = Column(Text, )
    menu_version_snapshot_data = Column(JSONB, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
