"""
Order Models - Auto-generated from SQL dump
Generated by scripts/generate_models.py
"""

from sqlalchemy import Column, String, Text, Integer, BigInteger, SmallInteger
from sqlalchemy import Boolean, DECIMAL, Float, DateTime, Date, Time
from sqlalchemy import ForeignKey, Index, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import UUID, JSONB, JSON
from sqlalchemy.sql import func
from app.core.db_session import Base
import uuid


class OrderAudit(Base):
    """Auto-generated model for order_audit table"""
    __tablename__ = "order_audit"

    order_audit_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    session_id = Column(UUID(as_uuid=True), index=True)
    order_version = Column(Integer, )
    modified_by = Column(UUID(as_uuid=True), )
    modification_reason = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderCharges(Base):
    """Auto-generated model for order_charges table"""
    __tablename__ = "order_charges"

    order_charges_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    order_item_id = Column(UUID(as_uuid=True), index=True)
    order_charges_type = Column(String(20), )
    order_charges_base_amount = Column(DECIMAL(precision=10, scale=2), )
    order_charges_taxable_amount = Column(DECIMAL(precision=10, scale=2), )
    order_charges_metadata_json = Column(JSONB, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderCustomerDetails(Base):
    """Auto-generated model for order_customer_details table"""
    __tablename__ = "order_customer_details"

    order_customer_details_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderDeliveryInfo(Base):
    """Auto-generated model for order_delivery_info table"""
    __tablename__ = "order_delivery_info"

    order_delivery_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    delivery_partner_id = Column(UUID(as_uuid=True), index=True)
    enable_delivery = Column(Boolean, default=False)
    delivery_type = Column(String(20), )
    delivery_slot = Column(Text, )
    delivery_address_id = Column(UUID(as_uuid=True), index=True)
    delivery_distance_km = Column(DECIMAL(precision=10, scale=2), )
    delivery_estimated_time = Column(DateTime(timezone=True), )
    delivery_actual_time = Column(DateTime(timezone=True), )
    delivery_person_id = Column(UUID(as_uuid=True), index=True)
    delivery_started_at = Column(DateTime(timezone=True), )
    delivery_completed_at = Column(DateTime(timezone=True), )
    delivery_otp = Column(String(20), )
    delivery_verification_method = Column(String(255), )
    delivery_tracking_url = Column(Text, )
    delivery_proof_url = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderDiningInfo(Base):
    """Auto-generated model for order_dining_info table"""
    __tablename__ = "order_dining_info"

    order_dining_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    table_id = Column(UUID(as_uuid=True), index=True)
    table_no = Column(Integer, )
    table_area = Column(String(255), )
    no_of_persons = Column(Integer, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderDiscount(Base):
    """Auto-generated model for order_discount table"""
    __tablename__ = "order_discount"

    order_discount_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_discount_type_id = Column(UUID(as_uuid=True), index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    order_item_id = Column(UUID(as_uuid=True), index=True)
    order_discount_amount = Column(DECIMAL(precision=10, scale=2), )
    order_discount_percentage = Column(DECIMAL(precision=5, scale=2), )
    order_discount_code = Column(String(20), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderInstruction(Base):
    """Auto-generated model for order_instruction table"""
    __tablename__ = "order_instruction"

    order_instruction_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    special_instructions = Column(Text, )
    kitchen_notes = Column(Text, )
    delivery_notes = Column(Text, )
    allergen_warning = Column(Text, )
    dietary_preferences = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderIntegrationSync(Base):
    """Auto-generated model for order_integration_sync table"""
    __tablename__ = "order_integration_sync"

    order_integration_sync_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    sync_status = Column(String(20), )
    sync_errors = Column(Text, )
    last_synced_at = Column(DateTime(timezone=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderInvoice(Base):
    """Auto-generated model for order_invoice table"""
    __tablename__ = "order_invoice"

    order_invoice_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    is_invoice_generated = Column(Boolean, default=False)
    invoice_url = Column(Text, )
    invoice_generated_at = Column(DateTime(timezone=True), )
    gstin = Column(String(255), )
    is_business_order = Column(Boolean, default=False)
    business_name = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderItem(Base):
    """Auto-generated model for order_item table"""
    __tablename__ = "order_item"

    order_item_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    menu_item_id = Column(UUID(as_uuid=True), index=True)
    menu_item_variation_id = Column(UUID(as_uuid=True), index=True)
    sku = Column(String(100), )
    hsn_code = Column(String(20), )
    category_id = Column(UUID(as_uuid=True), index=True)
    category_name = Column(String(100), )
    base_price = Column(DECIMAL(precision=10, scale=2), )
    discount_amount = Column(DECIMAL(precision=10, scale=2), )
    tax_amount = Column(DECIMAL(precision=10, scale=2), )
    addon_total = Column(DECIMAL(precision=10, scale=2), )
    is_available = Column(Boolean, default=True)
    unavailable_reason = Column(Text, )
    substitute_item_id = Column(UUID(as_uuid=True), index=True)
    cooking_instructions = Column(Text, )
    spice_level = Column(String(20), )
    customizations = Column(JSONB, )
    item_status = Column(String(50), )
    prepared_at = Column(DateTime(timezone=True), )
    served_at = Column(DateTime(timezone=True), )
    cancelled_at = Column(DateTime(timezone=True), )
    cancellation_reason = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderKitchenDetail(Base):
    """Auto-generated model for order_kitchen_detail table"""
    __tablename__ = "order_kitchen_detail"

    order_kitchen_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    order_item_id = Column(UUID(as_uuid=True), index=True)
    estimated_ready_time = Column(DateTime(timezone=True), )
    actual_ready_time = Column(DateTime(timezone=True), )
    preparation_start_time = Column(DateTime(timezone=True), )
    minimum_preparation_time = Column(Integer, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderNote(Base):
    """Auto-generated model for order_note table"""
    __tablename__ = "order_note"

    order_note_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    order_note_type = Column(String(20), )
    order_note_text = Column(Text, )
    order_note_visibility = Column(Boolean, default=True)
    order_note_added_by = Column(UUID(as_uuid=True), )
    is_important = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderPayment(Base):
    """Auto-generated model for order_payment table"""
    __tablename__ = "order_payment"

    order_payment_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    payment_order_id = Column(UUID(as_uuid=True), index=True)
    primary_transaction_id = Column(UUID(as_uuid=True), index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    order_payment_method_id = Column(UUID(as_uuid=True), index=True)
    tax_calculation_type_id = Column(UUID(as_uuid=True), index=True)
    paid_amount = Column(DECIMAL(precision=12, scale=2), )
    refund_amount = Column(DECIMAL(precision=12, scale=2), )
    wallet_amount_used = Column(DECIMAL(precision=12, scale=2), )
    loyalty_points_used = Column(Integer, )
    loyalty_points_earned = Column(Integer, )
    collect_cash = Column(Boolean, default=False)
    order_payment_status = Column(String(20), )
    order_payment_transaction_reference = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderPaymentMethod(Base):
    """Auto-generated model for order_payment_method table"""
    __tablename__ = "order_payment_method"

    order_payment_method_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_payment_method_code = Column(String(20), )
    order_payment_method_name = Column(String(255), )
    order_payment_method_is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderPriority(Base):
    """Auto-generated model for order_priority table"""
    __tablename__ = "order_priority"

    order_priority_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    is_urgent = Column(Boolean, default=False)
    priority_level = Column(Integer, )
    is_vip_order = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderScheduling(Base):
    """Auto-generated model for order_scheduling table"""
    __tablename__ = "order_scheduling"

    order_scheduling_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    is_preorder = Column(Boolean, default=False)
    is_scheduled = Column(Boolean, default=False)
    preorder_date = Column(Date, )
    preorder_time = Column(Time, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderSecurityDetail(Base):
    """Auto-generated model for order_security_detail table"""
    __tablename__ = "order_security_detail"

    order_security_detail_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    otp = Column(String(255), )
    callback_url = Column(Text, )
    callback_received_at = Column(DateTime(timezone=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderSourceType(Base):
    """Auto-generated model for order_source_type table"""
    __tablename__ = "order_source_type"

    order_source_type_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_source_type_code = Column(String(20), )
    order_source_type_name = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderStatusHistory(Base):
    """Auto-generated model for order_status_history table"""
    __tablename__ = "order_status_history"

    order_status_history_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    order_status_type_id = Column(UUID(as_uuid=True), index=True)
    order_status_changed_by = Column(UUID(as_uuid=True), )
    order_status_changed_at = Column(DateTime(timezone=True), server_default=func.now())
    order_status_notes = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderStatusType(Base):
    """Auto-generated model for order_status_type table"""
    __tablename__ = "order_status_type"

    order_status_type_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_status_code = Column(String(20), )
    order_status_name = Column(String(255), )
    order_status_description = Column(Text, )
    order_status_is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderTaxLine(Base):
    """Auto-generated model for order_tax_line table"""
    __tablename__ = "order_tax_line"

    order_tax_line_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_tax_line_charge_id = Column(UUID(as_uuid=True), index=True)
    order_item_id = Column(UUID(as_uuid=True), index=True)
    order_tax_line_tax_type = Column(String(20), )
    order_tax_line_percentage = Column(DECIMAL(precision=5, scale=2), )
    order_tax_line_amount = Column(DECIMAL(precision=10, scale=2), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderTotal(Base):
    """Auto-generated model for order_total table"""
    __tablename__ = "order_total"

    order_total_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    items_total = Column(DECIMAL(precision=12, scale=2), )
    addons_total = Column(DECIMAL(precision=12, scale=2), )
    charges_total = Column(DECIMAL(precision=12, scale=2), )
    discount_total = Column(DECIMAL(precision=12, scale=2), )
    tax_total = Column(DECIMAL(precision=12, scale=2), )
    platform_fee = Column(DECIMAL(precision=10, scale=2), )
    convenience_fee = Column(DECIMAL(precision=10, scale=2), )
    subtotal = Column(DECIMAL(precision=12, scale=2), )
    roundoff_amount = Column(DECIMAL(precision=10, scale=2), )
    total_before_tip = Column(DECIMAL(precision=12, scale=2), )
    tip_amount = Column(DECIMAL(precision=10, scale=2), )
    final_amount = Column(DECIMAL(precision=12, scale=2), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class OrderTypeTable(Base):
    """Auto-generated model for order_type_table table"""
    __tablename__ = "order_type_table"

    order_type_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_type_code = Column(String(20), )
    order_type_name = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
    ext_petpooja_order_type_id = Column(BigInteger, )
    restaurant_id = Column(UUID(as_uuid=True), index=True)
