"""
Other Models - Auto-generated from SQL dump
Generated by scripts/generate_models.py
"""

from sqlalchemy import Column, String, Text, Integer, BigInteger, SmallInteger
from sqlalchemy import Boolean, DECIMAL, Float, DateTime, Date, Time
from sqlalchemy import ForeignKey, Index, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import UUID, JSONB, JSON
from sqlalchemy.sql import func
from app.core.db_session import Base
import uuid


class AccountLock(Base):
    """Auto-generated model for account_lock table"""
    __tablename__ = "account_lock"

    account_lock_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), index=True)
    account_lock_at = Column(DateTime(timezone=True), )
    account_lock_until = Column(DateTime(timezone=True), )
    account_lock_reason = Column(Text, )
    account_lock_failed_attempts = Column(Integer, )
    account_lock_unlocked_at = Column(DateTime(timezone=True), )
    account_lock_unlocked_by = Column(UUID(as_uuid=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class Allergens(Base):
    """Auto-generated model for allergens table"""
    __tablename__ = "allergens"

    allergen_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    allergen_name = Column(String(255), nullable=False)
    allergen_description = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class Cuisines(Base):
    """Auto-generated model for cuisines table"""
    __tablename__ = "cuisines"

    cuisine_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    cuisine_name = Column(String(255), )
    cuisine_status = Column(String(20), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class Department(Base):
    """Auto-generated model for department table"""
    __tablename__ = "department"

    department_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    department_name = Column(String(255), )
    department_unique_code = Column(String(20), )
    department_description = Column(Text, )
    parent_department_id = Column(UUID(as_uuid=True), index=True)
    department_manager_id = Column(UUID(as_uuid=True), index=True)
    department_status = Column(String(20), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class DietaryRestrictions(Base):
    """Auto-generated model for dietary_restrictions table"""
    __tablename__ = "dietary_restrictions"

    dietary_restriction_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    dietary_restriction_name = Column(String(255), nullable=False)
    dietary_restriction_description = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class DietaryTypes(Base):
    """Auto-generated model for dietary_types table"""
    __tablename__ = "dietary_types"

    dietary_type_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    dietary_type_name = Column(String(255), )
    dietary_type_label = Column(String(255), )
    dietary_type_description = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class Discount(Base):
    """Auto-generated model for discount table"""
    __tablename__ = "discount"

    discount_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    discount_name = Column(String(255), )
    discount_description = Column(Text, )
    discount_type = Column(String(20), )
    discount_value = Column(DECIMAL(precision=10, scale=2), )
    discount_ordertype = Column(String(20), )
    discount_applicable_on = Column(Text, )
    discount_days = Column(Text, )
    discount_status = Column(String(20), )
    discount_rank = Column(Integer, )
    discount_on_total = Column(Boolean, default=False)
    discount_starts_at = Column(DateTime(timezone=True), )
    discount_time_from = Column(Time, )
    discount_time_to = Column(Time, )
    discount_min_amount = Column(DECIMAL(precision=10, scale=2), )
    discount_max_amount = Column(DECIMAL(precision=10, scale=2), )
    discount_has_coupon = Column(Boolean, default=False)
    discount_max_limit = Column(Integer, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
    ext_petpooja_discount_id = Column(BigInteger, )

class DiscountSchedule(Base):
    """Auto-generated model for discount_schedule table"""
    __tablename__ = "discount_schedule"

    discount_schedule_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    discount_id = Column(UUID(as_uuid=True), index=True)
    discount_schedule_day_of_week = Column(Integer, )
    discount_schedule_start_time = Column(Time, )
    discount_schedule_end_time = Column(Time, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class DiscountType(Base):
    """Auto-generated model for discount_type table"""
    __tablename__ = "discount_type"

    discount_type_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    discount_type_code = Column(String(20), )
    discount_type_name = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class EmailVerification(Base):
    """Auto-generated model for email_verification table"""
    __tablename__ = "email_verification"

    email_verification_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), index=True)
    email_verification_email = Column(String(255), )
    email_verification_otp = Column(String(255), )
    email_verification_expires_at = Column(DateTime(timezone=True), )
    email_verification_verified_at = Column(DateTime(timezone=True), )
    email_verification_attempts = Column(Integer, server_default=text("'0'"))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class EntitySlotConfig(Base):
    """Auto-generated model for entity_slot_config table"""
    __tablename__ = "entity_slot_config"

    slot_config_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    slot_capacity = Column(Integer, )
    slot_duration = Column(Integer, )
    slot_frequency = Column(Integer, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class Feedback(Base):
    """Auto-generated model for feedback table"""
    __tablename__ = "feedback"

    feedback_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    is_anonymous = Column(Boolean, default=False)
    contact_email = Column(String(255), )
    order_id = Column(UUID(as_uuid=True), index=True)
    booking_id = Column(UUID(as_uuid=True), index=True)
    product_id = Column(UUID(as_uuid=True), index=True)
    service_id = Column(UUID(as_uuid=True), index=True)
    title = Column(String(255), )
    feedback_text = Column(Text, nullable=False)
    rating = Column(Integer, )
    category_id = Column(UUID(as_uuid=True), index=True)
    feedback_type_id = Column(UUID(as_uuid=True), index=True)
    sentiment = Column(Text, )
    priority_id = Column(UUID(as_uuid=True), index=True)
    status_id = Column(UUID(as_uuid=True), index=True)
    assigned_to = Column(UUID(as_uuid=True), )
    assigned_at = Column(DateTime(timezone=True), )
    platform_id = Column(UUID(as_uuid=True), index=True)
    device_info = Column(String(255), )
    ip_address = Column(String(255), )
    user_agent = Column(String(255), )
    page_url = Column(Text, )
    is_urgent = Column(Boolean, default=False)
    is_featured = Column(Boolean, default=False)
    requires_followup = Column(Boolean, default=False)
    submitted_at = Column(DateTime(timezone=True), server_default=func.now())
    resolved_at = Column(DateTime(timezone=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class Languages(Base):
    """Auto-generated model for languages table"""
    __tablename__ = "languages"

    language_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    language_iso = Column(String(10), nullable=False)
    language_name = Column(String(255), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class LoginAttempt(Base):
    """Auto-generated model for login_attempt table"""
    __tablename__ = "login_attempt"

    login_attempt_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), index=True)
    login_attempt_email = Column(String(255), )
    login_attempt_success = Column(Boolean, default=False)
    login_attempt_ip_address = Column(String(255), )
    login_attempt_user_agent = Column(String(255), )
    login_attempt_failure_reason = Column(Text, )
    login_attempt_attempted_at = Column(DateTime(timezone=True), server_default=func.now())
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class LoyaltyTransaction(Base):
    """Auto-generated model for loyalty_transaction table"""
    __tablename__ = "loyalty_transaction"

    loyalty_txn_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    payment_transaction_id = Column(UUID(as_uuid=True), index=True)
    points_used = Column(Integer, server_default=text("'0'"))
    points_earned = Column(Integer, server_default=text("'0'"))
    points_balance_after = Column(Integer, server_default=text("'0'"))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class MealSlotTiming(Base):
    """Auto-generated model for meal_slot_timing table"""
    __tablename__ = "meal_slot_timing"

    meal_slot_timing_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    slot_config_id = Column(UUID(as_uuid=True), index=True)
    meal_type_id = Column(UUID(as_uuid=True), index=True)
    opening_time = Column(Time, )
    closing_time = Column(Time, )
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class MealType(Base):
    """Auto-generated model for meal_type table"""
    __tablename__ = "meal_type"

    meal_type_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    meal_type_name = Column(String(255), )
    display_order = Column(Integer, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class Orders(Base):
    """Auto-generated model for orders table"""
    __tablename__ = "orders"

    order_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    table_booking_id = Column(UUID(as_uuid=True), index=True)
    order_number = Column(BigInteger, )
    order_invoice_number = Column(String(20), )
    order_vr_order_id = Column(String(255), index=True)
    order_external_reference_id = Column(String(255), index=True)
    order_type_id = Column(UUID(as_uuid=True), index=True)
    order_source_type_id = Column(UUID(as_uuid=True), index=True)
    order_status_type_id = Column(UUID(as_uuid=True), index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class PasswordReset(Base):
    """Auto-generated model for password_reset table"""
    __tablename__ = "password_reset"

    password_reset_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), index=True)
    password_reset_token = Column(String(255), )
    password_reset_expires_at = Column(DateTime(timezone=True), )
    password_reset_used_at = Column(DateTime(timezone=True), )
    password_reset_ip_address = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class RefundReasonType(Base):
    """Auto-generated model for refund_reason_type table"""
    __tablename__ = "refund_reason_type"

    refund_reason_type_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    refund_reason_code = Column(String(20), )
    refund_reason_name = Column(String(255), )
    refund_reason_description = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class RefundStatusType(Base):
    """Auto-generated model for refund_status_type table"""
    __tablename__ = "refund_status_type"

    refund_status_type_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    refund_status_code = Column(String(20), nullable=False)
    refund_status_name = Column(String(255), nullable=False)
    refund_status_description = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class RestaurantFaq(Base):
    """Auto-generated model for restaurant_faq table"""
    __tablename__ = "restaurant_faq"

    restaurant_faq_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    restaurant_faq_question = Column(Text, nullable=False)
    restaurant_faq_answer = Column(Text, nullable=False)
    restaurant_faq_category = Column(String(100), )
    restaurant_faq_display_order = Column(Integer, server_default=text("'0'"))
    restaurant_faq_is_active = Column(Boolean, default=True)
    restaurant_faq_view_count = Column(Integer, server_default=text("'0'"))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class RestaurantPolicy(Base):
    """Auto-generated model for restaurant_policy table"""
    __tablename__ = "restaurant_policy"

    restaurant_policy_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    restaurant_policy_category = Column(String(100), nullable=False)
    restaurant_policy_title = Column(Text, nullable=False)
    restaurant_policy_description = Column(Text, )
    restaurant_is_active = Column(Boolean, default=True)
    restaurant_effective_from = Column(Date, )
    restaurant_effective_until = Column(Date, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class RestaurantTable(Base):
    """Auto-generated model for restaurant_table table"""
    __tablename__ = "restaurant_table"

    restaurant_id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid() NOT NULL"), index=True)
    chain_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    iframe = Column(Text, nullable=True)
    branch_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    is_deleted = Column(Boolean, default=False)
    deleted_at = Column(DateTime(timezone=True), )

class Role(Base):
    """Auto-generated model for role table"""
    __tablename__ = "role"

    role_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    role_name = Column(String(255), nullable=False)
    role_unique_code = Column(String(20), nullable=False)
    role_description = Column(Text, )
    role_level = Column(Integer, )
    is_system_role = Column(Boolean, default=False)
    role_status = Column(String(20), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class RoundRobinPool(Base):
    """Auto-generated model for round_robin_pool table"""
    __tablename__ = "round_robin_pool"

    round_robin_pool_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    round_robin_pool_name = Column(String(255), )
    round_robin_pool_type = Column(String(20), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class RoundRobinPoolMember(Base):
    """Auto-generated model for round_robin_pool_member table"""
    __tablename__ = "round_robin_pool_member"

    round_robin_pool_member_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    round_robin_pool_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    user_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    round_robin_pool_member_priority = Column(Integer, )
    round_robin_pool_member_is_active = Column(Boolean, default=True)
    round_robin_pool_member_last_assigned_at = Column(DateTime(timezone=True), )
    round_robin_pool_member_total_assignments = Column(Integer, server_default=text("'0'"))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class ShiftTiming(Base):
    """Auto-generated model for shift_timing table"""
    __tablename__ = "shift_timing"

    shift_timing_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    shift_timing_name = Column(String(255), )
    shift_timing_shift_code = Column(String(20), )
    shift_timing_start_time = Column(Time, )
    shift_timing_end_time = Column(Time, )
    shift_timing_break_duration_minutes = Column(Integer, )
    shift_timing_is_overnight = Column(Boolean, default=False)
    shift_timing_status = Column(String(20), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class TableBookingInfo(Base):
    """Auto-generated model for table_booking_info table"""
    __tablename__ = "table_booking_info"

    table_booking_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    table_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    meal_slot_timing_id = Column(UUID(as_uuid=True), index=True)
    previous_slot_id = Column(UUID(as_uuid=True), index=True)
    customer_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    occasion_id = Column(UUID(as_uuid=True), index=True)
    party_size = Column(Integer, )
    booking_date = Column(Date, )
    booking_time = Column(Time, )
    booking_status = Column(String(20), )
    special_request = Column(Text, )
    cancellation_reason = Column(Text, )
    is_advance_booking = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class TableBookingOccasionInfo(Base):
    """Auto-generated model for table_booking_occasion_info table"""
    __tablename__ = "table_booking_occasion_info"

    occasion_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    occasion_type = Column(String(255), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class TableInfo(Base):
    """Auto-generated model for table_info table"""
    __tablename__ = "table_info"

    table_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    table_number = Column(Integer, )
    table_capacity = Column(Integer, )
    table_type = Column(String(255), )
    is_active = Column(Boolean, default=True)
    floor_location = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class TableSpecialFeatures(Base):
    """Auto-generated model for table_special_features table"""
    __tablename__ = "table_special_features"

    table_feature_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    table_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    feature_name = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class Tag(Base):
    """Auto-generated model for tag table"""
    __tablename__ = "tag"

    tag_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    tag_name = Column(String(255), )
    tag_type = Column(String(20), )
    tag_description = Column(Text, )
    tag_color = Column(String(255), )
    tag_status = Column(String(20), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class TagsFeedback(Base):
    """Auto-generated model for tags_feedback table"""
    __tablename__ = "tags_feedback"

    tag_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    tag_name = Column(String(255), nullable=False)
    description = Column(Text, )
    color_code = Column(String(255), )
    usage_count = Column(Integer, server_default=text("'0'"))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class TaxCalculationType(Base):
    """Auto-generated model for tax_calculation_type table"""
    __tablename__ = "tax_calculation_type"

    tax_calculation_type_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    tax_calculation_type_code = Column(String(255), )
    tax_calculation_type_name = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class Taxes(Base):
    """Auto-generated model for taxes table"""
    __tablename__ = "taxes"

    tax_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    tax_name = Column(String(255), )
    tax_percentage = Column(DECIMAL(precision=5, scale=2), )
    tax_type = Column(String(50), )
    tax_status = Column(String(20), )
    tax_ordertype = Column(String(50), )
    tax_total = Column(DECIMAL(precision=12, scale=2), )
    tax_rank = Column(Integer, )
    tax_description = Column(Text, )
    tax_consider_in_core_amount = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
    ext_petpooja_tax_id = Column(BigInteger, )

class User(Base):
    """Auto-generated model for user table"""
    __tablename__ = "user"

    user_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_email = Column(String(255), )
    user_mobile_no = Column(String(255), )
    user_password_hash = Column(Text, )
    user_status = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class VariationGroups(Base):
    """Auto-generated model for variation_groups table"""
    __tablename__ = "variation_groups"

    variation_group_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    variation_group_name = Column(String(255), )
    variation_group_selection_type = Column(String(255), )
    variation_group_min_selection = Column(Integer, )
    variation_group_max_selection = Column(Integer, )
    variation_group_status = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class VariationOptions(Base):
    """Auto-generated model for variation_options table"""
    __tablename__ = "variation_options"

    variation_option_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    variation_group_id = Column(UUID(as_uuid=True), index=True)
    menu_item_id = Column(UUID(as_uuid=True), index=True)
    option_name = Column(String(255), )
    option_price_modifier = Column(DECIMAL(precision=10, scale=2), )
    option_rank = Column(Integer, )
    option_status = Column(String(255), )
    dietary_type_id = Column(UUID(as_uuid=True), index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
