"""
Payment Models - Auto-generated from SQL dump
Generated by scripts/generate_models.py
"""

from sqlalchemy import Column, String, Text, Integer, BigInteger, SmallInteger
from sqlalchemy import Boolean, DECIMAL, Float, DateTime, Date, Time
from sqlalchemy import ForeignKey, Index, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import UUID, JSONB, JSON
from sqlalchemy.sql import func
from app.core.db_session import Base
import uuid


class PaymentAuditLog(Base):
    """Auto-generated model for payment_audit_log table"""
    __tablename__ = "payment_audit_log"

    audit_log_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    payment_order_id = Column(UUID(as_uuid=True), index=True)
    payment_transaction_id = Column(UUID(as_uuid=True), index=True)
    payment_refund_id = Column(UUID(as_uuid=True), index=True)
    event_type = Column(Text, )
    event_source = Column(Text, )
    request_payload = Column(JSONB, )
    response_payload = Column(JSONB, )
    gateway_event_id = Column(Text, index=True)
    gateway_event_type = Column(Text, )
    initiated_by = Column(UUID(as_uuid=True), )
    ip_address = Column(String(255), )
    user_agent = Column(String(255), )
    event_status = Column(String(20), )
    error_message = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class PaymentExternalMapping(Base):
    """Auto-generated model for payment_external_mapping table"""
    __tablename__ = "payment_external_mapping"

    external_mapping_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    payment_order_id = Column(UUID(as_uuid=True), index=True)
    payment_transaction_id = Column(UUID(as_uuid=True), index=True)
    external_system = Column(Text, )
    external_payment_id = Column(Text, index=True)
    external_order_id = Column(Text, index=True)
    sync_status = Column(String(20), )
    sync_attempts = Column(Integer, server_default=text("'0'"))
    last_synced_at = Column(DateTime(timezone=True), )
    sync_error = Column(Text, )
    external_response = Column(JSONB, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class PaymentGateway(Base):
    """Auto-generated model for payment_gateway table"""
    __tablename__ = "payment_gateway"

    payment_gateway_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    payment_gateway_code = Column(String(20), )
    payment_gateway_name = Column(String(255), )
    payment_gateway_is_active = Column(Boolean, default=True)
    payment_gateway_config = Column(JSONB, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class PaymentOrder(Base):
    """Auto-generated model for payment_order table"""
    __tablename__ = "payment_order"

    payment_order_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    payment_gateway_id = Column(UUID(as_uuid=True), index=True)
    gateway_order_id = Column(Text, index=True)
    payment_order_status = Column(String(20), )
    order_amount = Column(DECIMAL(precision=12, scale=2), )
    order_currency = Column(String(3), server_default=text("'INR'"))
    payment_link_url = Column(Text, )
    payment_link_id = Column(String(255), index=True)
    payment_link_short_url = Column(Text, )
    payment_link_expires_at = Column(DateTime(timezone=True), )
    retry_count = Column(Integer, server_default=text("'0'"))
    max_retry_attempts = Column(Integer, server_default=text("'3'"))
    notes = Column(Text, )
    metadata_ = Column(JSONB, name="metadata")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class PaymentRefund(Base):
    """Auto-generated model for payment_refund table"""
    __tablename__ = "payment_refund"

    payment_refund_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    payment_transaction_id = Column(UUID(as_uuid=True), index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    order_item_id = Column(UUID(as_uuid=True), index=True)
    payment_order_id = Column(UUID(as_uuid=True), index=True)
    payment_gateway_id = Column(UUID(as_uuid=True), index=True)
    gateway_refund_id = Column(String(255), index=True)
    gateway_payment_id = Column(String(255), index=True)
    refund_amount = Column(DECIMAL(precision=12, scale=2), )
    refund_currency = Column(String(3), server_default=text("'INR'"))
    refund_reason_type_id = Column(UUID(as_uuid=True), index=True)
    refund_reason_notes = Column(Text, )
    refund_status_type_id = Column(UUID(as_uuid=True), index=True)
    initiated_by = Column(UUID(as_uuid=True), )
    approved_by = Column(UUID(as_uuid=True), )
    processing_notes = Column(Text, )
    gateway_response = Column(JSONB, )
    refund_initiated_at = Column(DateTime(timezone=True), )
    refund_processed_at = Column(DateTime(timezone=True), )
    refund_completed_at = Column(DateTime(timezone=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class PaymentRetryAttempt(Base):
    """Auto-generated model for payment_retry_attempt table"""
    __tablename__ = "payment_retry_attempt"

    retry_attempt_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    payment_order_id = Column(UUID(as_uuid=True), index=True)
    payment_transaction_id = Column(UUID(as_uuid=True), index=True)
    attempt_number = Column(Integer, )
    gateway_payment_id = Column(Text, index=True)
    attempt_status = Column(String(20), )
    failure_reason = Column(Text, )
    failure_code = Column(String(20), )
    retry_metadata = Column(JSONB, )
    attempted_at = Column(DateTime(timezone=True), server_default=func.now())
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class PaymentSplit(Base):
    """Auto-generated model for payment_split table"""
    __tablename__ = "payment_split"

    payment_split_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    payment_transaction_id = Column(UUID(as_uuid=True), index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    split_party_type = Column(String(20), )
    split_party_id = Column(UUID(as_uuid=True), index=True)
    split_amount = Column(DECIMAL(precision=12, scale=2), )
    split_percentage = Column(DECIMAL(precision=5, scale=2), )
    split_currency = Column(String(3), server_default=text("'INR'"))
    delivery_partner_id = Column(UUID(as_uuid=True), index=True)
    is_settled = Column(Boolean, default=False)
    settled_at = Column(DateTime(timezone=True), )
    settlement_reference = Column(String(255), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class PaymentStatusType(Base):
    """Auto-generated model for payment_status_type table"""
    __tablename__ = "payment_status_type"

    payment_status_type_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    payment_status_code = Column(String(20), )
    payment_status_name = Column(String(255), )
    payment_status_description = Column(Text, )
    payment_status_is_terminal = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class PaymentTransaction(Base):
    """Auto-generated model for payment_transaction table"""
    __tablename__ = "payment_transaction"

    payment_transaction_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    payment_order_id = Column(UUID(as_uuid=True), index=True)
    order_id = Column(UUID(as_uuid=True), index=True)
    restaurant_id = Column(UUID(as_uuid=True), index=True)
    customer_id = Column(UUID(as_uuid=True), index=True)
    payment_gateway_id = Column(UUID(as_uuid=True), index=True)
    gateway_payment_id = Column(Text, index=True)
    gateway_transaction_id = Column(Text, index=True)
    gateway_signature = Column(Text, )
    order_payment_method_id = Column(UUID(as_uuid=True), index=True)
    payment_method_details = Column(JSONB, )
    transaction_amount = Column(DECIMAL(precision=12, scale=2), )
    amount_paid = Column(DECIMAL(precision=12, scale=2), )
    amount_due = Column(DECIMAL(precision=12, scale=2), )
    transaction_currency = Column(String(3), server_default=text("'INR'"))
    gateway_fee = Column(DECIMAL(precision=10, scale=2), )
    gateway_tax = Column(DECIMAL(precision=10, scale=2), )
    net_amount = Column(DECIMAL(precision=12, scale=2), )
    payment_status_type_id = Column(UUID(as_uuid=True), index=True)
    failure_reason = Column(Text, )
    failure_code = Column(String(20), )
    error_description = Column(Text, )
    bank_name = Column(Text, )
    card_network = Column(Text, )
    card_type = Column(Text, )
    card_last4 = Column(String(4), )
    wallet_provider = Column(Text, )
    upi_vpa = Column(Text, )
    customer_email = Column(Text, )
    customer_contact = Column(Text, )
    gateway_response = Column(JSONB, )
    attempted_at = Column(DateTime(timezone=True), )
    authorized_at = Column(DateTime(timezone=True), )
    captured_at = Column(DateTime(timezone=True), )
    settled_at = Column(DateTime(timezone=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class PaymentWebhookLog(Base):
    """Auto-generated model for payment_webhook_log table"""
    __tablename__ = "payment_webhook_log"

    webhook_log_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    payment_gateway_id = Column(UUID(as_uuid=True), index=True)
    webhook_event_id = Column(Text, index=True)
    webhook_event_type = Column(Text, )
    webhook_payload = Column(JSONB, )
    webhook_signature = Column(Text, )
    signature_verified = Column(Boolean, default=False)
    processing_status = Column(String(20), )
    processing_attempts = Column(Integer, server_default=text("'0'"))
    processing_error = Column(Text, )
    extracted_payment_id = Column(Text, index=True)
    extracted_order_id = Column(Text, index=True)
    matched_payment_transaction_id = Column(Text, index=True)
    source_ip = Column(Text, )
    received_at = Column(DateTime(timezone=True), server_default=func.now())
    processed_at = Column(DateTime(timezone=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
