"""
User Models - Auto-generated from SQL dump
Generated by scripts/generate_models.py
"""

from sqlalchemy import Column, String, Text, Integer, BigInteger, SmallInteger
from sqlalchemy import Boolean, DECIMAL, Float, DateTime, Date, Time
from sqlalchemy import ForeignKey, Index, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import UUID, JSONB, JSON
from sqlalchemy.sql import func
from app.core.db_session import Base
import uuid


class UserAuditTrail(Base):
    """Auto-generated model for user_audit_trail table"""
    __tablename__ = "user_audit_trail"

    user_audit_trail_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), index=True)
    user_audit_trail_table_name = Column(String(255), )
    user_audit_trail_record_id = Column(UUID(as_uuid=True), index=True)
    user_audit_trail_action = Column(Text, )
    user_audit_trail_old_values = Column(JSONB, )
    user_audit_trail_new_values = Column(JSONB, )
    user_audit_trail_changed_by = Column(UUID(as_uuid=True), )
    user_audit_trail_changed_at = Column(DateTime(timezone=True), server_default=func.now())
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class UserContact(Base):
    """Auto-generated model for user_contact table"""
    __tablename__ = "user_contact"

    user_contact_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), index=True)
    user_contact_type = Column(String(255), )
    user_contact_value = Column(String(255), )
    user_contact_is_primary = Column(Boolean, default=False)
    user_contact_is_verified = Column(Boolean, default=False)
    user_contact_verified_at = Column(DateTime(timezone=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class UserDepartment(Base):
    """Auto-generated model for user_department table"""
    __tablename__ = "user_department"

    user_department_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), index=True)
    department_id = Column(UUID(as_uuid=True), index=True)
    user_department_is_primary = Column(Boolean, default=False)
    user_department_assigned_at = Column(DateTime(timezone=True), server_default=func.now())
    user_department_assigned_by = Column(UUID(as_uuid=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class UserLoginHistory(Base):
    """Auto-generated model for user_login_history table"""
    __tablename__ = "user_login_history"

    user_login_history_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), index=True)
    user_login_history_login_at = Column(DateTime(timezone=True), )
    user_login_history_logout_at = Column(DateTime(timezone=True), )
    user_login_history_ip_address = Column(String(255), )
    user_login_history_user_agent = Column(String(255), )
    user_login_history_device_type = Column(String(255), )
    user_login_history_location_data = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class UserProfile(Base):
    """Auto-generated model for user_profile table"""
    __tablename__ = "user_profile"

    user_profile_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), index=True)
    user_profile_first_name = Column(String(255), )
    user_profile_last_name = Column(String(255), )
    user_profile_display_name = Column(String(255), )
    user_profile_gender = Column(String(255), )
    user_profile_date_of_birth = Column(Date, )
    user_profile_profile_picture_url = Column(Text, )
    user_profile_bio = Column(Text, )
    user_profile_address_line1 = Column(Text, )
    user_profile_address_line2 = Column(Text, )
    user_profile_city = Column(String(255), )
    user_profile_state = Column(String(255), )
    user_profile_country = Column(String(255), )
    user_profile_postal_code = Column(String(255), )
    user_profile_timezone = Column(String(255), )
    user_profile_language_preference = Column(Text, )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class UserRole(Base):
    """Auto-generated model for user_role table"""
    __tablename__ = "user_role"

    user_role_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), index=True)
    role_id = Column(UUID(as_uuid=True), index=True)
    user_role_assigned_at = Column(DateTime(timezone=True), server_default=func.now())
    user_role_assigned_by = Column(UUID(as_uuid=True), )
    user_role_expires_at = Column(DateTime(timezone=True), )
    user_role_is_primary = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class UserSession(Base):
    """Auto-generated model for user_session table"""
    __tablename__ = "user_session"

    user_session_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), index=True)
    user_session_token = Column(String(255), )
    user_session_refresh_token = Column(String(255), )
    user_session_ip_address = Column(String(255), )
    user_session_user_agent = Column(String(255), )
    user_session_device_info = Column(Text, )
    user_session_expires_at = Column(DateTime(timezone=True), )
    user_session_last_activity_at = Column(DateTime(timezone=True), )
    user_session_logged_out_at = Column(DateTime(timezone=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class UserShiftAssignment(Base):
    """Auto-generated model for user_shift_assignment table"""
    __tablename__ = "user_shift_assignment"

    user_shift_assignment_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), index=True)
    shift_timing_id = Column(UUID(as_uuid=True), index=True)
    user_shift_assignment_effective_from = Column(Date, )
    user_shift_assignment_effective_to = Column(Date, )
    user_shift_assignment_assigned_at = Column(DateTime(timezone=True), server_default=func.now())
    user_shift_assignment_assigned_by = Column(UUID(as_uuid=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)

class UserTag(Base):
    """Auto-generated model for user_tag table"""
    __tablename__ = "user_tag"

    user_tag_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), index=True)
    tag_id = Column(UUID(as_uuid=True), index=True)
    user_tag_added_at = Column(DateTime(timezone=True), server_default=func.now())
    user_tag_added_by = Column(UUID(as_uuid=True), )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(UUID(as_uuid=True), )
    updated_by = Column(UUID(as_uuid=True), )
    deleted_at = Column(DateTime(timezone=True), )
    is_deleted = Column(Boolean, default=False)
